### ISSUE TITLE
./dream_go --extract kgs_bal.sgf > kgs_big.bin?

### ISSUE THREAD

**Issue by ecilay** [Chicoryn/dream-go#28]
how to make this command?
there is no dream-go exe file..
./dream_go --extract kgs_bal.sgf > kgs_big.bin

**Comment by Chicoryn** [comment]
If you have built the project using cargo then then you can find `dream_go` in the directory `target/release`. In the README I shortened the path to just `./dream_go` to keep it simple. The full serie of commands, including building the binary if you have not done so already, is:

```bash
cargo build --release
./target/release/dream_go --extract kgs_bal.sgf > kgs_big.bin
...
```

You can of course also copy it to the current directory for future easy access:

```bash
cargo build --release && cp target/release/dream_go ./dream_go
./dream_go --extract kgs_bal.sgf > kgs_big.bin
...
```

**Comment by ecilay** [comment]
thanks this help!
When i build it gets me error below:



`error[E0554]: #![feature] may not be used on the stable release channel
   --> /Users/alliey/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.0.0/src/lib.rs:104:32
    |
104 | #![cfg_attr(feature="nightly", feature(unreachable))]
    |                                ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `lazy_static`.

To learn more, run the command again with --verbose.`

**Comment by ecilay** [comment]
thanks this help!
When i build it gets me error below:



`error[E0554]: #![feature] may not be used on the stable release channel
   --> /Users/alliey/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.0.0/src/lib.rs:104:32
    |
104 | #![cfg_attr(feature="nightly", feature(unreachable))]
    |                                ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

Build failed, waiting for other jobs to finish...
error: Could not compile `lazy_static`.

To learn more, run the command again with --verbose.`

**Comment by Chicoryn** [comment]
_Dream Go_ requires the nightly branch of rust for various reasons mostly related to performance. You will need to "upgrade" your current stable branch to nightly to compile. It seems like you are using `rustup` so the following commands should work:

```bash
rustup toolchain install nightly
rustup default nightly
```

If this worked then you should see a version similar to the the one below when running `cargo --version`:

```bash
$ cargo --version
cargo 0.26.0-nightly (1d6dfea44 2018-01-26)
```

Once you are done compiling _Dream Go_ and you want to switch back to stable you can do so by typing:

```bash
rustup default stable
```

PS: Here are some binaries you can use if you are running Linux (linked against CUDA 9.1 and cuDNN 7). Unfortunately I do not have access to a Mac or Windows machine, so if you are using that then we'll have to see if we can make the compilation work.

[dreamgo-0.5.0_amd64.tar.gz](https://github.com/Chicoryn/dream-go/files/1768073/dreamgo-0.5.0_amd64.tar.gz)
