### ISSUE TITLE
2022 TCGA Computer Go Tournament is coming!

### ISSUE THREAD

**Issue by CGLemon** [Chicoryn/dream-go#60]
TCGA is same as ICGA compute game tournament. Many compute games will be held. The 9x9 Go is one of them. I want to invite you to play with us. The computer Go game tournament will be held on 5/14. Registration deadlines is 5/7 in Taiwan.

The rule is very similar to the Tromp-Taylor rules, the detail are here

Board Size 9

    Time Control is 10 minutes Sudden Death.
    Area Scoring(chinese-rule).
    No suicide allowed.
    Komi 7
    Positional Superko is used.

Board Size 19

    Time Control is 30 minutes Sudden Death.
    Area Scoring(chinese-rule).
    No suicide allowed.
    Komi 7.5
    Positional Superko is used.

The game platform is [KGS](https://www.gokgs.com/). To connect the server by [kgsGtp.jar](https://www.gokgs.com/download.jsp). Must to register a new KGS account.

Tournament registration side is [here](https://tcga.tw/tournament2022/en/)

You may ask me anything If you have the questions.

**Comment by Chicoryn** [comment]
Closing this as I don't have anything ready for this years tournament.
